### ISSUE TITLE
cordova-plugin-chrome-apps-common dependency build error

### ISSUE THREAD

**Issue by 255kb** [MobileChromeApps/cordova-plugin-chrome-apps-bluetooth#4]
I get a build error when Cordova is trying to fetch the plugin "cordova-plugin-chrome-apps-common"

It seems that there is a problem with the version in the plugin.xml file: 
    <dependency id="cordova-plugin-chrome-apps-common@1" />

Maybe "1" should be "1.0.7" ?

**Comment by agrieve** [comment]
What is the error that you're seeing (please paste it in), and what version of cordova or cca are you using?

**Comment by 255kb** [comment]
Sorry my bad, I am still using an old version of Cordova which do not accept plugins with new NPM names.
Thanks for your time
